description = 'A lightweight and responsive theme for Hugo based on Pico CSS'
license = 'MIT'
licenselink = 'https://github.com/gren236/gren-theme/blob/main/LICENSE'
name = 'Gren Theme'
# The home page of the theme, where the source can be found
homepage = 'https://github.com/gren236/gren-theme'

min_version = "0.116.0"

# Taxonomy terms
features = ['some', 'awesome', 'features']
tags = ['blog', 'company']

# If the theme has a single author
[author]
homepage = 'https://gren.dev'
name = 'Egor Rudkov'
